### ISSUE TITLE
[MSHARED-105] StringIndexOutOfBoundsException in AbstractMavenReportRenderer.applyPattern

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-reporting-impl#73]
**[Elifarley Callado Coelho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elifarley@yahoo.com)** opened **[MSHARED-105](https://issues.apache.org/jira/browse/MSHARED-105?redirect=false)** and commented

Maybe the problem is in 'ProjectSummaryReport$ProjectSummaryRenderer.renderBody'.

Here is the stack trace:

```
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] String index out of range: -221
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.StringIndexOutOfBoundsException: String index out of range: -221
	at java.lang.String.substring(String.java:1768)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.applyPattern(AbstractMavenReportRenderer.java:533)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.linkPatternedText(AbstractMavenReportRenderer.java:353)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.tableCell(AbstractMavenReportRenderer.java:213)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.tableCell(AbstractMavenReportRenderer.java:193)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.tableRow(AbstractMavenReportRenderer.java:225)
	at org.apache.maven.report.projectinfo.ProjectSummaryReport$ProjectSummaryRenderer.renderBody(ProjectSummaryReport.java:109)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:65)
	at org.apache.maven.report.projectinfo.ProjectSummaryReport.executeReport(ProjectSummaryReport.java:39)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:101)
	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:139)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:269)
	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:101)
	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:129)
	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:447)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:333)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:126)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Attachments:**
- [MNG-3489-test-and-fix.patch.gz](https://issues.apache.org/jira/secure/attachment/12719088/MNG-3489-test-and-fix.patch.gz) (_901 bytes_)

**Issue Links:**
- [MSHARED-28](https://issues.apache.org/jira/browse/MSHARED-28) StringIndexOutOfBoundsException in AbstractMavenReportRenderer

**Comment by jira-importer** [comment]
**[Hervé Boutemy](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=hboutemy)** commented

please attach a testcase to reproduce the problem

**Comment by jira-importer** [comment]
**[Elifarley Callado Coelho](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=elifarley@yahoo.com)** commented

I've attached a very simple unit test case and a proposed fix for it, which is quite simple too.

This patch is against https://svn.apache.org/repos/asf/maven/shared/branches/maven-reporting-impl-2.0.4.x

**Comment by jira-importer** [comment]
**[John Dennis Casey](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdcasey)** commented

Pushing to 2.0.11 so we can have a smaller set of high-value issues to target for the next release (2.0.10).
